apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              service:
                name: back
                port:
                  number: 8080
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
