apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "5431"
      port: 5431
      targetPort: 5432
  selector:
    io.kompose.service: db
  type: NodePort
status:
  loadBalancer: {}
