services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  gradle_image: gradle:7.5.0-jdk11
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - pre-deploy
  - deploy-dev
  - deploy-feature
  - deploy-pre-prod

build-job:
  stage: build
  image: ${gradle_image}
  script:
    - echo "Compiling the code..."
    - gradle assemble
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: ${gradle_image}
  script:
    - echo "Running unit tests..."
    - gradle check
    - echo "Complete"

add-namespaces-job:
  stage: pre-deploy
  script:
    - cd .chart
    - kubectl apply -f namespaces.yaml

deploy-dev-job:
  stage: deploy-dev
  script:
    - cd .chart
    - echo "Deploying application..."
    - helm upgrade soc-network ./docker-compose --install --namespace soc-network-dev --values ./docker-compose/values.yaml --values ./docker-compose/values-soc-network-dev.yaml
    - echo "Application successfully deployed."

deploy-feature-job:
  stage: deploy-feature
  script:
    - cd .chart
    - echo "Deploying application..."
    - helm upgrade soc-network ./docker-compose --install --namespace soc-network-feature --values ./docker-compose/values.yaml --values ./docker-compose/values-soc-network-feature.yaml
    - echo "Application successfully deployed."

deploy-pre-prod-job:
  stage: deploy-pre-prod
  script:
    - cd .chart
    - echo "Deploying application..."
    - helm upgrade soc-network ./docker-compose --install --namespace soc-network-preprod --values ./docker-compose/values.yaml --values ./docker-compose/values-soc-network-preprod.yaml
    - echo "Application successfully deployed."

