services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  gradle_image: gradle:7.5.0-jdk11
  DOKCER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIT: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: ${gradle_image}
  script:
    - echo "Compiling the code..."
    - gradle assemble
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: ${gradle_image}
  script:
    - echo "Running unit tests..."
    - gradle check
    - echo "Complete"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
