version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
  back:
    image: wonderkot/social-network:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/social_network
    ports:
      - "8080:8080"
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
    depends_on:
      - db